### ISSUE TITLE
notificações

### ISSUE THREAD

**Issue by michelmelo** [romuloalves/superplayer-control-chrome#26]
cara conseguir fazer se quiser podemos fala :)
![captura de tela 2014-10-22 14 04 51](https://cloud.githubusercontent.com/assets/159223/4736436/58d76a0c-59ec-11e4-92ae-472a05aa9b47.png)

**Comment by romuloalves** [comment]
@michelmelo , acredito não ser mais necessária esta implementação, o próprio Superplayer já criou notificações. Concorda?

**Comment by michelmelo** [comment]
@romuloalves  pois, tbm acredito. done
